apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
    version: "v2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
      - name: gateway
        image: ghcr.io/ustkost/quickticket-gateway:2a69b1c5f9796ee47f540122048f9626f9300ec0
        imagePullPolicy: Always 
        ports:
        - containerPort: 8080
        env:
        - name: EVENTS_URL
          value: "http://events:8081"
        - name: PAYMENTS_URL
          value: "http://payments:8082"
        - name: GATEWAY_TIMEOUT_MS
          value: "5000"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          periodSeconds: 5
          failureThreshold: 2
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: gateway
